// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesWebAPI.Models;

#nullable disable

namespace SalesWebAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("SalesWebAPI.Models.Buyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Buyers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tom"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jack"
                        });
                });

            modelBuilder.Entity("SalesWebAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FuckToy",
                            Price = 228.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "shit",
                            Price = 1337.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Smth",
                            Price = 2344.0
                        });
                });

            modelBuilder.Entity("SalesWebAPI.Models.ProvidedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalesPointId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesPointId");

                    b.ToTable("ProvidedProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            ProductQuantity = 2,
                            SalesPointId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            ProductQuantity = 2,
                            SalesPointId = 1
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            ProductQuantity = 2,
                            SalesPointId = 2
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 2,
                            ProductQuantity = 2,
                            SalesPointId = 2
                        });
                });

            modelBuilder.Entity("SalesWebAPI.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesPointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SalesPointId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyerId = 1,
                            Date = "12.05.2020",
                            SalesPointId = 1,
                            Time = "12:34:02",
                            TotalAmount = 228.0
                        },
                        new
                        {
                            Id = 2,
                            BuyerId = 2,
                            Date = "28.08.2021",
                            SalesPointId = 2,
                            Time = "10:45:23",
                            TotalAmount = 3681.0
                        });
                });

            modelBuilder.Entity("SalesWebAPI.Models.SaleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductIdAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            ProductIdAmount = 228,
                            ProductQuantity = 1,
                            SaleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            ProductIdAmount = 1337,
                            ProductQuantity = 1,
                            SaleId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            ProductIdAmount = 2344,
                            ProductQuantity = 1,
                            SaleId = 2
                        });
                });

            modelBuilder.Entity("SalesWebAPI.Models.SalesPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalesPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Eldorado"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DnsShop"
                        });
                });

            modelBuilder.Entity("SalesWebAPI.Models.ProvidedProduct", b =>
                {
                    b.HasOne("SalesWebAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesWebAPI.Models.SalesPoint", null)
                        .WithMany("ProvidedProducts")
                        .HasForeignKey("SalesPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesWebAPI.Models.Sale", b =>
                {
                    b.HasOne("SalesWebAPI.Models.Buyer", null)
                        .WithMany("SalesIds")
                        .HasForeignKey("BuyerId");

                    b.HasOne("SalesWebAPI.Models.SalesPoint", "SalesPoint")
                        .WithMany()
                        .HasForeignKey("SalesPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesPoint");
                });

            modelBuilder.Entity("SalesWebAPI.Models.SaleData", b =>
                {
                    b.HasOne("SalesWebAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesWebAPI.Models.Sale", null)
                        .WithMany("SalesData")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesWebAPI.Models.Buyer", b =>
                {
                    b.Navigation("SalesIds");
                });

            modelBuilder.Entity("SalesWebAPI.Models.Sale", b =>
                {
                    b.Navigation("SalesData");
                });

            modelBuilder.Entity("SalesWebAPI.Models.SalesPoint", b =>
                {
                    b.Navigation("ProvidedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
